//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prevista
    {
        public int Id { get; set; }
        public int IdAbonado { get; set; }
        public int IdTarifa { get; set; }
        public int IdSector { get; set; }
        public string Direccion { get; set; }
        public string FolioReal { get; set; }
    
        public Abonado Abonado { get; set; }
        public Sector Sectore { get; set; }
        public Tarifa Tarifa { get; set; }
    }
}
