//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prevista
    {
        public int Id { get; set; }
        public int IdAbonado { get; set; }
        public int IdTarifa { get; set; }
        public int IdSector { get; set; }
        public string Direccion { get; set; }
        public string FolioReal { get; set; }
    
        public virtual Abonado Abonado { get; set; }
        public virtual Sectore Sectore { get; set; }
        public virtual Tarifa Tarifa { get; set; }
    }
}
